name: Zoran-Anticatastase-Rhetorique-Politique
version: "1.0"
license: MIT
doi: 10.5281/zenodo.17007992
generated: 2025-08-30T11:50:41.695869Z
contact: tabary01@gmail.com
keywords:
  - Anticatastase
  - Rhétorique politique
  - Figures de style
  - Langage et pouvoir
  - Retournement sémantique
  - Rhétorique antique
  - Cicéron
  - Quintilien
  - Rhétorique contemporaine
  - Discours politique
  - Argumentation
  - Manipulation du langage
  - Antiphrase vs anticatastase
  - Populisme
  - Radicalité
  - Utopisme
  - Étiquetage politique
  - Réseaux sociaux
  - Hashtags inversés
  - Judo verbal
  - Stratégie discursive
  - Narratif politique
  - Communication politique
  - Zoran aSiM
  - IA mimétique
  - Détection NLP
  - Glyphnet
  - ΔM11.3
  - EthicChain
  - Aegis Layer
